name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: root
        uses: docker://rootproject/root-ubuntu16:6.10
      - name: add parameter
        run: echo 'set(CMAKE_MODULE_PATH /usr/local/share/root/cmake/ROOTConfig.cmake)' >> CmakeLists.txt
      - name: cmake
        run: cmake .
      - name: make
        run: make
      - name: make check
        run: make check
      - name: make distcheck
        run: make distcheck
